# A. Define the name for this action
name: DeployToGitHubPages

# C. Controls when the action will run, in this case only checkins on master branch
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # D. Check out the code
    - uses: actions/checkout@v2

    # E. Build and Publish the Blazor WebAssembly App
    - name: Publish app
      run: dotnet publish BlazorMatchGame.csproj -c Release -o release --nologo

    # G. This step commits all files from the wwwroot folder to the gh-pages branch
    - name: GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        BRANCH: gh-pages
        FOLDER: release/wwwroot
    
